name: Cruft Update

on:
  workflow_dispatch:

concurrency:
  group: cruft-update-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  cruft:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.5

      - name: Install dependencies
        run: pip install cruft jello

      - name: Update project structure
        run: |
          cruft update -y
      - name: Get new template version
        # extract new cooiecutter template version
        run: |
          echo "TEMPLATE_COMMIT=$(cat .cruft.json | jello -r "_['commit'][:8]")" >> $GITHUB_ENV
      # behaviour if PR already exists: https://github.com/marketplace/actions/create-pull-request#action-behaviour
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.REPO_SETUP_TOKEN }}
          commit-message: >-
            chore: update project structure to ${{ env.TEMPLATE_COMMIT }}
          title: "[Actions] Auto-Sync cookiecutter template"
          body: ""
          branch: cruft-update
          delete-branch: true
